trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Sets FOO to be "some value" in the script and the next ones
  - bash: |
      FOO="runtime value"
      echo "##vso[task.setvariable variable=FOO]$FOO"

  # Using the $() syntax during "compile time", the pipeline expands the variable
  - bash: |
      echo "$(FOO)"

  # Using an environment variable in the script context at "runtime", bash expands the variable
  - bash: |
      echo "$FOO"